### ISSUE TITLE
Returns the name of the executable within the path

### ISSUE THREAD

**Issue by davesnx** [MarkTiedemann/fastlist#3]
Hey @MarkTiedemann 

Using `fkill` I found out the output of the processes name includes the path as `name`. The issue is opened in the fkill repo (https://github.com/sindresorhus/fkill-cli/issues/78), but I trace it down into your package where I believe the process lists gets rendered. 

Is there any chance to add the process name without the path? My good old days of C are gone but I'm happy to take a look if you are busy.

Thanks and let me know! :D

**Comment by MarkTiedemann** [comment]
> but I trace it down into your package where I believe the process lists gets rendered

That's incorrect. The linked issue happens on MacOS, this binary only works on Windows.

**Comment by davesnx** [comment]
My bad, sorry for the spam

**Comment by MarkTiedemann** [comment]
No worries, @davesnx.
